server:
  port: 8088

spring:
  application:
    name: reporting-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password123@localhost:27017/tesp_report_db?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME:tesp-report-exports}
    region: ${AWS_REGION:us-east-1}
